name: Php Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install local-php-security-checker
      run: wget -O 'local-php-security-checker' 'https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64'

    - name: Check download
      run: chmod +x ./local-php-security-checker && ls -al

    - name: Check
      run: ./local-php-security-checker

