name: PHPunit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: docker login
      env:
        AZ_DOCKER_REGISTRY_HOST: ${{ secrets.AZ_DOCKER_REGISTRY_HOST }}
        AZ_DOCKER_REGISTRY_USER: ${{ secrets.AZ_DOCKER_REGISTRY_USER }}
        AZ_DOCKER_REGISTRY_PWD: ${{ secrets.AZ_DOCKER_REGISTRY_PWD }}
      run: |
        echo  ${AZ_DOCKER_REGISTRY_PWD} | docker login -u ${AZ_DOCKER_REGISTRY_USER} ${AZ_DOCKER_REGISTRY_HOST} --password-stdin

    - name: mount service
      run: make up && make install

    - name: Exec tests
      run: sleep 15 && make test

    - name: Unmount
      run: make down

    - name: remove data
      run: docker logout && rm -f /home/runner/.docker/config.jso
